### ISSUE TITLE
SamplePluginVB throws null exception on event action creation

### ISSUE THREAD

**Issue by mcsSolutions** [HomeSeer/Plugin-SDK#60]
HS4 Version 4.0.1.5

In InitNewConfigPage the _logTypeOptions select list has not yet been instantiated at the time the call to this procedure was made.  A similar issue was reported for triggers where the onNewTrigger method was being called before the New() method completed.

The specific error in the procedure is System.ArgumentNullException shown below.  The process to create it is to create a new event and for the Action select the Sample Plugin Action - Write To Log from the selector.

System.ArgumentNullException
  HResult=0x80004003
  Message=Value cannot be null.
Parameter name: options
  Source=PluginSdk
  StackTrace:
   at HomeSeer.Jui.Views.SelectListView..ctor(String id, String name, List`1 options, ESelectListType style, Int32 selection)
   at HomeSeer.Jui.Views.PageFactory.WithDropDownSelectList(String id, String name, List`1 options, Int32 selection)
   at HSPI_HomeSeerSamplePlugin_VB.WriteLogSampleActionType.InitNewConfigPage() in C:\Users\Public\Documents\LaptopVM\Sample-Plugin-VB-master\WriteLogSampleActionType.vb:line 198
   at HSPI_HomeSeerSamplePlugin_VB.WriteLogSampleActionType.OnNewAction() in C:\Users\Public\Documents\LaptopVM\Sample-Plugin-VB-master\WriteLogSampleActionType.vb:line 91
   at HomeSeer.PluginSdk.Events.AbstractActionType.InflateActionFromData()

**Comment by jldubz** [comment]
Tracked by PSDK-23

This is noted as resolved internally. Checking to see if the code on GitHub matches.

**Comment by jldubz** [comment]
I have updated the code for sampleplugin-vb on GitHub with the latest internal set.  See commit https://github.com/HomeSeer/Sample-Plugin-VB/commit/12e183e0d8911b44d1178721e2b4b6c00b7f2050

Please let me know if you are still encountering this issue.
